version: "3.8"
services:

  richlist:
    env_file:
      - .env
    build: .
    ports:
      - "8001:8001"
    volumes:
      - "./database/:/home/database"
    command: python richlist/main.py

  price:
    env_file:
      - .env
    build: .
    ports:
      - "8002:8002"
    volumes:
      - "./database/:/home/database"
    command: python price/main.py